clining/urls.py
from django.urls import path
from .views import *

app_name = "myprint"

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('gallary/', gallary, name='gallary'),
    path('gallary/<int:pk>/', gallary_details, name='gallary-detail'),
    path('guests/', guests, name='guests'),
    path('services/', services, name='services'),
    path('product-detail/', product_detail, name='product'),
    path('product-detail/<int:pk>/', product_detail, name='product-detail'),
]

config/urls.py
# from django.conf.urls.i18n import i18n_patterns
# from django.contrib import admin
# from django.urls import path, include
# from django.conf import settings
# from django.conf.urls import handler404
# from django.conf.urls.static import static
# from django.utils.translation import gettext_lazy as _

# urlpatterns = [
#     path("i18n/", include("django.conf.urls.i18n")),
#     path('', include('clining.urls')),
#     path('rosetta/', include('rosetta.urls')),

# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += i18n_patterns(path("admin/", admin.site.urls))
# urlpatterns += i18n_patterns(path("", include('clining.urls')))
# urlpatterns += i18n_patterns(path('rosetta/', include('rosetta.urls')))

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _
from django.conf import settings

from django.conf.urls import handler404
from django.conf.urls.static import static


urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('clining.urls')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/main/about.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}

     <!-- Start Breadcrumb 
    ============================================= -->
    <div class="breadcrumb-area text-center shadow dark text-light bg-cover" style="background-image: url({% static 'img/banner/21.jpg' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h1>About Us</h1>
                    <ul class="breadcrumb">
                        <li><a href="{% url 'myprint:home' %}"><i class="fas fa-home"></i> {% trans "Home" %}</a></li>
                        <li class="active">{% trans "About" %}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Start About
    ============================================= -->
    <div class="about-style-two-area default-padding">
        <div class="container">
            <div class="row align-center">
                <div class="col-lg-6 about-style-two">
                    <div class="thumb">
                        <img src="{% static 'img/thumb/11.jpg' %}" alt="Thumb">
                        <img src="{% static 'img/thumb/12.jpg' %}" alt="Thumb">
                        <div class="fun-fact">
                            <div class="counter">
                                <div class="timer" data-to="50" data-speed="5000">{% trans "50" %}</div>
                                <div class="operator">{% trans "+" %}</div>
                            </div>
                            <span class="medium">{% trans "Team Member" %}</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 about-style-three">
                    <h4 class="sub-heading">{% trans "About Cleaning Agency " %}</h4>
                    <h2 class="heading">{% trans "We are committed to give <br> our best services" %}</h2>
                    <p>
                        {% trans "Friendly bachelor entrance to on by. Extremity as if breakfast agreement. Off now mistress provided out horrible opinions. Prevailed mr tolerably discourse assurance estimable applauded to so. Him everything melancholy uncommonly but solicitude inhabiting projection." %}
                    </p>
                    <ul>
                        <li>{% trans "Service Monitoring" %}</li>
                        <li>{% trans "Fast Communication" %}</li>
                        <li>{% trans "Customer Support Live Chat" %}</li>
                        <li>{% trans "Information for Any Services" %}</li>
                    </ul>
                    <a class="btn btn-theme primary effect btn-md" href="#">{% trans "Contact Us" %}</a>
                </div>
            </div>
        </div>
    </div>
    <!-- End About -->

    
    {% endblock content %}

templates/main/contact.html
{% extends 'base.html' %} 
{% load static %} 
{% load i18n %}

{% block content %}
     <!-- Start Breadcrumb 
    ============================================= -->
    <div class="breadcrumb-area text-center shadow dark text-light bg-cover" style="background-image: url({% static 'img/banner/10.jpg'%});">

        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h1>Contact Us</h1>
                    <ul class="breadcrumb">
                        <li><a href="{% url 'myprint:home' %}"><i class="fas fa-home"></i>{% trans " Home" %}</a></li>
                        <li class="active">{% trans "Contact" %}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Start Contact Area 
    ============================================= -->
    <div id="contact" class="contact-area default-padding">
        <div class="container">
            <div class="contact-content">
                <div class="row">
                    <div class="col-lg-4 info">
                        <div class="content text-light text-center">
                            <div class="thumb">

                                <img src="{{contact_us_banner.location_call_img.url}}" alt="Thumb">

                            </div>
                            <ul>
                                <li>
                                    <i class="fal fa-map-marker-alt"></i>
                                    <p>
                                        {{location}}
                                    </p>
                                </li>
                                <li>
                                    <i class="fal fa-phone-alt"></i>
                                    <p>
                                        {{extra_phone1}} <br> {{extra_phone2}}
                                    </p>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-8 contact-form-box">
                        <div class="form-box">
                            <h2>{% trans "Let's talk?" %}</h2>
                            <p>
                                {% trans "It's all about the humans behind a brand and those experiencing it, we're right there. In the middle performance quick." %}
                            </p>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            {{ form.name }}
                                            <span class="alert-error"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">

                                            {{ form.phone_number }}
                                            <span class="alert-error"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group comments">
                                            {{ form.description }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <button type="submit" name="submit" id="submit">
                                            Send Message <i class="fa fa-paper-plane"></i>
                                        </button>
                                    </div>
                                </div>
                                <!-- Alert Message -->
                                <div class="col-lg-12 alert-notification">
                                    <div id="message" class="alert-msg"></div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Contact Area -->

    <!-- Star Google Maps
    ============================================= -->
    <div class="maps-area">
        <div class="container">
            <div class="google-maps">
                <div class="row">
                    <div class="col-lg-12">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d14767.262289338461!2d70.79414485000001!3d22.284975!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1424308883981"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Google Maps -->

{% endblock %}

templates/main/gallary-datails.html
{% extends 'base.html' %}
{% load static %}

{% extends 'base.html' %}

{% load static %}
{% block content %}

     <!-- Start Breadcrumb 
    ============================================= -->
    <div class="breadcrumb-area text-center shadow dark text-light bg-cover" style="background-image: url({% static 'img/banner/6.jpg' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    {% for pro in project %}
                        <!-- Single Item -->
                        <div class="pf-item" style="position: absolute; left: 0%; top: 0px;">
                            <div class="project-style-two">
                                <img src="{{pro.gallary.image.url}}" alt="Thumb">
                                <div class="info">
                                    <span>{{pro.title   }}</span>
                                    <h4><a href="">{{pro.description}}</a></h4>
                                </div>
                            </div>
                        </div>
                        <!-- End Single Item -->
                        {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Star Project Details Area
    ============================================= -->
    <div class="project-details-area default-padding">
        <div class="container">
            <div class="project-details-items">
                <div class="thumb">
                    <img src="{% static 'img/banner/7.jpg' %}" alt="Thumb">
                </div>
                <div class="top-info">
                    <div class="row">
                        <div class="col-lg-12 left-info">
                            <h2>{% trans "Making A Clean Difference" %}</h2>
                            <p>
                                {% trans "New had happen unable uneasy. Drawings can followed improved out sociable not. Earnestly so do instantly pretended. See general few civilly amiable pleased account carried. Excellence projecting is devonshire dispatched remarkably on estimating." %}
                            </p>
                            <p>
                                {% trans "Netus lorem rutrum arcu dignissim at sit morbi phasellus nascetur eget urna potenti cum vestibulum cras. Tempor nonummy metus lobortis. Sociis velit etiam, dapibus. Lectus vehicula pellentesque cras posuere tempor facilisi habitant lectus rutrum pede quisque hendrerit parturient posuere mauris ad elementum fringilla facilisi volutpat fusce pharetra felis sapien varius quisque class convallis praesent est sollicitudin donec nulla venenatis, cursus fermentum netus posuere sociis porta risus habitant malesuada nulla habitasse hymenaeos. Viverra curabitur nisi vel sollicitudin dictum natoqu." %}
                            </p>
                        </div>

                    </div>
                </div>


            </div>
        </div>
    </div>
    <!-- End Project Details Area -->
    {% endblock content %}

templates/main/gallary.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
Gallery
{% block content %}

     <!-- Start Breadcrumb 
    ============================================= -->
    <div class="breadcrumb-area text-center shadow dark text-light bg-cover" style="background-image: url({% static 'img/banner/6.jpg' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h1>{% trans 'Latest Projects' %}</h1>
                    <ul class="breadcrumb">
                        <li><a href="{% url 'myprint:home' %}"><i class="fas fa-home"></i>{% trans 'Home' %}</a></li>
                        <li class="active">{% trans 'Projects' %}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Start Project Area
    ============================================= -->
    <div class="project-area overflow-hidden default-padding">
        <div class="container">
            <div class="project-items-area">
                <div class="masonary">
                    <div id="portfolio-grid" class="gallery-items colums-3" style="position: relative; height: 708.3px;">
                        {% for pro in projects %}
                        <!-- Single Item -->
                        <div class="pf-item" style="position: absolute; left: 0%; top: 0px;">
                            <div class="project-style-two">
                                <img src="{{pro.image.url}}" alt="Thumb">
                                <div class="info">
                                    <span>{{pro.place}}</span>
                                    <h4><a href="{% url 'gallary-detail' pro.pk %}">{{pro.service}}</a></h4>
                                </div>
                            </div>
                        </div>
                        <!-- End Single Item -->
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Projects Area -->
{% endblock %}

templates/main/product-detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="breadcrumb-area text-center shadow dark text-light bg-cover"
         style="background-image: url({% static 'img/banner/6.jpg' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h1>Project Details</h1>
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="fas fa-home"></i> Project</a></li>
                        <li class="active">Details</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Star Project Details Area
    ============================================= -->
    <div class="project-details-area default-padding">
        <div class="container">
            {% for detail in detailCarusel %}
                <div class="project-details-items">
                <div class="thumb">
                    <img src="{{ detail.caruselimage.image.url }}" alt="Thumb">
                </div>
                <div class="top-info">
                    <div class="row">
                        <div class="col-lg-7 left-info">
                            <h2>{{ detail.title }}</h2>
                            <p>{{ detail.description }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/main/service_count.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}
     <!-- Start Breadcrumb 
    ============================================= -->
    <div class="breadcrumb-area text-center shadow dark text-light bg-cover" style="background-image: url({% static 'img/banner/21.jpg' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h1>You Choose</h1>
                    <ul class="breadcrumb">
                        <li><a href="{% url 'myprint:home' %}"><i class="fas fa-home"></i> Home</a></li>
                        <li class="active">Services</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Start there how me fuck mouse of your wife  Features Area 
    ============================================= -->
  
    <!-- End Fun Factor Area -->


    <div class="appoinment-area bg-theme">
        <div class="container">
            <div class="row align-center">
                <div class="col-lg-6">
                    <div class="thumb">
                        <img src="{% static 'img/illustration/6.png' %}" alt="illustration">
                    </div>
                </div>
                <div class="col-lg-5 offset-lg-1 form-content">
                    <div class="form-items">
                        <h2>Свой тариф</h2>
                        <p>
                            Get a quick response within 24 hours
                        </p>
                        <form>
                           
                           <div class="form-box">

                            <select name="" id="1">
                                {% for rm in order %}
                                    <option value="1">{{rm.name}}</option>
                                {% endfor %}
                            </select>
                            {% for sr in order %}
                            <div class="form-checkbox">
                                <input type="checkbox" class="rate__input" id="checkbox_1">
                                <label for="checkbox_1" class="rate__lable">{{sr.name}}</label>
                            </div>
                            {% endfor %}
                           </div>

                           <div class="row" style="margin-top: 25px;">
                            <div class="col-lg-12">
                                <button class="btn-animation dark border" type="submit" name="submit" id="submit">
                                    <span>Get it <i class="fas fa-angle-right"></i></span>
                                </button>
                            </div>
                        </div>
                            


                        <div class="form-price">
                            <h2></span></h2>
                        </div>
                        </form>
                    </div>

                   
                </div>
            </div>
        </div>
    </div>


    {% endblock content %}

templates/main/services.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}
    <!-- Start Breadcrumb
   ============================================= -->
    <div class="breadcrumb-area text-center shadow dark text-light bg-cover"
         style="background-image: url({% static 'img/banner/21.jpg' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h1>Our Services</h1>
                    <ul class="breadcrumb">
                        <li><a href="{% url 'myprint:home' %}"><i class="fas fa-home"></i> {% trans "Home" %}</a></li>
                        <li class="active">{% trans "Services" %}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Start there how me fuck mouse of your wife  Features Area
    ============================================= -->

    <!-- End Fun Factor Area -->


   <!-- Start Pricing Area 

    ============================================= -->
    <div class="pricing-area default-padding-bottom bottom-less" style="padding-top: 50px;">
        <!-- Fixed Shape -->
        <div class="fixed-sahpe-bottom">
            <img src="{% static 'img/shape/19.png' %}" alt="Shape">
        </div>
        <!-- End Fixed Shape -->
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <div class="site-heading text-center">

                        <h2>Quality leader among cleaning <br> Companies in the industry!</h2>
                        <div class="devider"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="pricing pricing-simple">
                <div class="row">
                    <div class="owl-carousel owl-theme owl-loaded">
                        <div class="owl-stage-outer">
                            <div class="owl-stage-rl">

                                {% for i in card %}
                                <div class="owl-item"> 
                                    <div class="col-lg-12 single-item">
                                        <div class="pricing-item ">

                                            <div class="pricing-header">
                                                <h4>{{i.name}}</h4>
                                            </div>
                                            <div class="price">
                                                <h2><sup>$</sup>{{i.price}}</h2>
                                                <p>{{i.detail}}</p>
                                            </div>

                                                <ul>
                                                    {% for ser in i.service.all %}
                                                    <li>{{ser.name}}<i {% if ser.is_exist == True %} class="fas fa-check-circle"{% else %} class="fas fa-times-circle"{% endif %}></i></li>
                                                    {% endfor %}
                                                </ul>
                                            <a class="btn btn-dark effect btn-sm" href="{% url 'myprint:contact' %}">Book Now</a>

                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>

                    </div>     

                </div>
            </div>
        </div>

    </div>
    <!-- End Pricing Area -->
    <div class="appoinment-area bg-theme">
        <div class="container">
            <div class="row align-center">
                <div class="col-lg-6">
                    <div class="thumb">
                        <img src="{% static 'img/illustration/6.png' %}" alt="illustration">
                    </div>
                </div>
                <div class="col-lg-5 offset-lg-1 form-content">
                    <div class="form-items">
                        <h2>Создай свой тариф</h2>
                        <p>
                            Get a quick response within 24 hours
                        </p>


                        <!-- forma -->
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-box">

                                <select name="option[]" id="select__calc">
                                    {% for rm in cat %}
                                    <option value="{{rm.name}}-{{rm.price}}">{{rm.name}}</option>
                                    {% endfor %}
                                </select>
                                {% for sr in servic %}
                                <div class="form-checkbox">
                                    <input type="checkbox" id="{{sr.name}}" name="checks[]" class="rate__input input__calc" value="{{sr.name}}-{{sr.price}}">
                                    <label for="{{sr.name}}"  class="rate__lable">{{sr.name}}</label>
                                </div>
                                {% endfor %}
                            </div>
                            


                            <div class="row" style="gap: 20px; margin-top: 25px;">
                                <div class="col-lg-12">
                                    <button class="btn-animation dark border calculate__button" type="submit" name="submit" id="submit">
                                        <span>Calculate<i class="fas fa-angle-right"></i></span>
                                    </button>
                                </div>
                            
                            <div class="col-lg-12">
                                <button class="btn-animation dark border" href="{% url 'myprint:contact' %}" name="submit" id="submit">
                                    <span>Get it <i class="fas fa-angle-right"></i></span>
                                </button>
                            </div>
                            <div class="form-price">
                                <h2><span>--</span>SUM</h2>
                            </div>
                        </div>

                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>
    

{% endblock content %}
{% block script %}
    <script>
        const result = document.querySelector(".form-price h2");
        const calculateButton = document.querySelector(".calculate__button");
        const baseUrl = location.origin;
        const parentDiv = document.querySelector(".form-box");
        const select = document.querySelector(".select__options");
        const selectOption = document.querySelector(".select__calc");
        const inputCalc = document.querySelectorAll(".input__calc");
        const forms = document.querySelector('form')


        //culc
        function calcTotal(e) {
            e.preventDefault();
            const prices = [select__calc.value];
            inputCalc.forEach(item => {
                if (item.checked) {
                    return prices.push(item.value);
                }
            });

            const totalPrice = prices.reduce((prevValue, currenValue) => Number(prevValue) + Number(currenValue), 0);

            result.innerText = totalPrice;
        }

        calculateButton.addEventListener("click", calcTotal);

        const obj = {
            roomname: "",
            roomprice: 1200,
            services: [
                {name: "Sanuzel", price: 15000}
            ],
            totalPrice;
        }

        function postData(form) {
            form.addEventListener('submit', (e) => {
                e.preventDefault();


                const statusMessage = document.createElement('div')
                statusMessage.classList.add('status');
                statusMessage.textContent = message.loading;
                form.append(statusMessage);

                const request = new XMLHttpRequest();
                request.open('POST', 'serviceprice');

                // request.setRequestHeader('Content-type' , 'miltipart/form-data')
                const formData = new FormData(form);

                request.send(formData);

                request.addEventListener('load', () => {
                    if (request.status === 200) {
                        console.log(request.response);
                        statusMessage.textContent = message.success;
                    } else {

                        statusMessage.textContent = message.failure;
                    }
                })
            });
        }

        const message = {
            loading: 'Loading',
            success: 'Thank you, we will contact you soon',
            failure: 'Fail '
        }

    </script>
{% endblock %}


    {% endblock content %}
    {% block script %}
    <script>
        const result = document.querySelector(".form-price h2");
        const form = document.querySelector(".calculate");
        const calculateButton = document.querySelector(".calculate__button");

        const parentDiv = document.querySelector(".form-box");
        const select = document.querySelector(".select__options");
        const selectOption = document.querySelector(".select__calc");
        const inputCalc = document.querySelectorAll(".input__calc");
        //culc 



        function calcTotal (e) {
            e.preventDefault();
            const prices = [select__calc.value.split("-")[1]];
            inputCalc.forEach(item => {
                if(item.checked) {
                    return prices.push(item.value.split("-")[1]);
                }
            });
    
            const totalPrice = prices.reduce((prevValue, currenValue) => Number(prevValue) + Number(currenValue), 0);
            
            result.innerText = totalPrice.toLocaleString(
                undefined,
                {
                    minimumFractionDigits: 1
                }
            );
        }
        calculateButton.addEventListener("click", calcTotal);
    
    </script>
    {% endblock %}  